<?php
session_start();

if (isset($_GET['lang']) && in_array($_GET['lang'], ['es', 'en'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

$lang = $_SESSION['lang'] ?? 'es';

$translations = [
    'es' => [
        'nav_home'        => 'Inicio',
        'nav_properties'  => 'Propiedades',
        'nav_about'       => 'Nosotros',
        'nav_contact'     => 'Contacto',
        'nav_blog'        => 'Blog',
        'hero_tagline'    => 'Inversión Inmobiliaria de Lujo',
        'hero_sub'        => 'en el Caribe Mexicano',
        'hero_desc'       => 'Conectamos a nuestros clientes con las mejores oportunidades en las zonas más exclusivas de México: Riviera Maya, Riviera Nayarit y Los Cabos.',
        'hero_cta1'       => 'Ver Propiedades',
        'hero_cta2'       => 'Contáctanos',
        'stat_years'      => 'Años de Experiencia',
        'stat_homes'      => 'Viviendas Vendidas',
        'stat_projects'   => 'Proyectos Inmobiliarios',
        'feat_title'      => 'Propiedades Destacadas',
        'feat_sub'        => 'Desarrollos exclusivos seleccionados para maximizar tu inversión',
        'from'            => 'Desde',
        'roi'             => 'ROI Anual',
        'rooms'           => 'Recámaras',
        'area'            => 'Superficie',
        'btn_details'     => 'Ver Detalles',
        'btn_contact'     => 'Solicitar Info',
        'about_title'     => '¿Por qué elegir Solumare?',
        'about_sub'       => 'Más de 30 años guiando inversiones exitosas en los destinos más codiciados de México',
        'about_p1'        => 'Somos líderes en bienes raíces de lujo en la Riviera Maya. Nuestra experiencia y red de desarrolladores de primer nivel nos permiten ofrecerte proyectos que no solo son hermosos, sino altamente rentables.',
        'about_p2'        => 'Cada propiedad en nuestro portafolio pasa por un riguroso proceso de selección para garantizar plusvalía, calidad constructiva y retorno de inversión superior al mercado.',
        'about_f1'        => 'Asesoría Personalizada',
        'about_f2'        => 'Propiedades Certificadas',
        'about_f3'        => 'Gestión de Renta',
        'about_f4'        => 'Retorno Garantizado',
        'zones_title'     => 'Nuestras Zonas',
        'zones_sub'       => 'Presencia en los destinos más exclusivos de México',
        'contact_title'   => 'Habla con un Experto',
        'contact_sub'     => 'Nuestro equipo está listo para guiarte en cada paso de tu inversión',
        'form_name'       => 'Nombre Completo',
        'form_email'      => 'Correo Electrónico',
        'form_phone'      => 'Teléfono / WhatsApp',
        'form_interest'   => 'Propiedad de Interés',
        'form_select'     => 'Selecciona una opción',
        'form_msg'        => 'Mensaje',
        'form_send'       => 'Enviar Mensaje',
        'form_success'    => '¡Mensaje enviado! Te contactaremos pronto.',
        'form_error'      => 'Error al enviar. Intenta de nuevo.',
        'footer_rights'   => 'Todos los derechos reservados.',
        'footer_privacy'  => 'Política de Privacidad',
        'footer_terms'    => 'Términos y Condiciones',
        'footer_desc'     => 'Agencia inmobiliaria de lujo especializada en propiedades exclusivas en las zonas más cotizadas de México.',
        'amenities'       => 'Amenidades',
        'delivery'        => 'Entrega',
        'units'           => 'Unidades',
        'certification'   => 'Certificación',
        'prop_back'       => '← Volver a Propiedades',
        'prop_invest'     => 'Datos de Inversión',
        'prop_amenities'  => 'Amenidades Premium',
        'prop_gallery'    => 'Galería',
        'prop_location'   => 'Ubicación',
        'contact_now'     => 'Agendar Cita',
        'whatsapp'        => 'WhatsApp',
        'read_more'       => 'Leer más',
        'all_properties'  => 'Todas las Propiedades',
        'filter_all'      => 'Todos',
        'filter_tulum'    => 'Tulum',
        'filter_isla'     => 'Isla Mujeres',
        'filter_cabos'    => 'Los Cabos',
    ],
    'en' => [
        'nav_home'        => 'Home',
        'nav_properties'  => 'Properties',
        'nav_about'       => 'About Us',
        'nav_contact'     => 'Contact',
        'nav_blog'        => 'Blog',
        'hero_tagline'    => 'Luxury Real Estate Investment',
        'hero_sub'        => 'in the Mexican Caribbean',
        'hero_desc'       => 'We connect our clients with the best investment opportunities in the most exclusive areas of Mexico: Riviera Maya, Riviera Nayarit and Los Cabos.',
        'hero_cta1'       => 'View Properties',
        'hero_cta2'       => 'Contact Us',
        'stat_years'      => 'Years of Experience',
        'stat_homes'      => 'Homes Sold',
        'stat_projects'   => 'Real Estate Projects',
        'feat_title'      => 'Featured Properties',
        'feat_sub'        => 'Exclusive developments selected to maximize your investment',
        'from'            => 'From',
        'roi'             => 'Annual ROI',
        'rooms'           => 'Bedrooms',
        'area'            => 'Area',
        'btn_details'     => 'View Details',
        'btn_contact'     => 'Request Info',
        'about_title'     => 'Why choose Solumare?',
        'about_sub'       => 'Over 30 years guiding successful investments in Mexico\'s most coveted destinations',
        'about_p1'        => 'We are leaders in luxury real estate in the Riviera Maya. Our experience and network of top-tier developers allow us to offer you projects that are not only beautiful, but highly profitable.',
        'about_p2'        => 'Every property in our portfolio goes through a rigorous selection process to ensure capital appreciation, construction quality, and above-market return on investment.',
        'about_f1'        => 'Personalized Advisory',
        'about_f2'        => 'Certified Properties',
        'about_f3'        => 'Rental Management',
        'about_f4'        => 'Guaranteed Return',
        'zones_title'     => 'Our Zones',
        'zones_sub'       => 'Presence in Mexico\'s most exclusive destinations',
        'contact_title'   => 'Talk to an Expert',
        'contact_sub'     => 'Our team is ready to guide you through every step of your investment',
        'form_name'       => 'Full Name',
        'form_email'      => 'Email Address',
        'form_phone'      => 'Phone / WhatsApp',
        'form_interest'   => 'Property of Interest',
        'form_select'     => 'Select an option',
        'form_msg'        => 'Message',
        'form_send'       => 'Send Message',
        'form_success'    => 'Message sent! We will contact you soon.',
        'form_error'      => 'Error sending. Please try again.',
        'footer_rights'   => 'All rights reserved.',
        'footer_privacy'  => 'Privacy Policy',
        'footer_terms'    => 'Terms & Conditions',
        'footer_desc'     => 'Luxury real estate agency specializing in exclusive properties in the most sought-after areas of Mexico.',
        'amenities'       => 'Amenities',
        'delivery'        => 'Delivery',
        'units'           => 'Units',
        'certification'   => 'Certification',
        'prop_back'       => '← Back to Properties',
        'prop_invest'     => 'Investment Data',
        'prop_amenities'  => 'Premium Amenities',
        'prop_gallery'    => 'Gallery',
        'prop_location'   => 'Location',
        'contact_now'     => 'Schedule Appointment',
        'whatsapp'        => 'WhatsApp',
        'read_more'       => 'Read more',
        'all_properties'  => 'All Properties',
        'filter_all'      => 'All',
        'filter_tulum'    => 'Tulum',
        'filter_isla'     => 'Isla Mujeres',
        'filter_cabos'    => 'Los Cabos',
    ],
];

function t(string $key): string {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}

function langUrl(string $targetLang): string {
    $params = $_GET;
    $params['lang'] = $targetLang;
    return '?' . http_build_query($params);
}
